In [1]:
import torch

Single Layer NN


In [2]:
## Sigmoid activation function
def activation(x) :
    return 1/(1+torch.exp(-x))

In [3]:
## Generate some data
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [4]:
y = activation(torch.sum(features*weights) + bias)

In [5]:
weights.view(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [9]:
y = activation(torch.mm(features,weights.view(5,1)) + bias)

Multilayer NN

In [10]:
torch.manual_seed(7)
features = torch.randn((1,3))
n_input = features.shape[1]
n_hidden = 2
n_output = 1

w1 = torch.randn(n_input,n_hidden)
w2 = torch.randn(n_hidden,n_output)

b1 = torch.randn((1,n_hidden))
b2 = torch.randn((1,n_output))

In [11]:
h = activation(torch.mm(features,w1) + b1)
output = activation(torch.mm(h,w2) + b2)
print(output)

tensor([[0.3171]])


numpy to torch and back

In [12]:
import numpy as np

In [18]:
a = np.random.rand(4,3)
b = torch.from_numpy(a)
b.numpy()

array([[0.92039356, 0.31198323, 0.59624366],
       [0.20867766, 0.23432166, 0.99914556],
       [0.63533321, 0.15813693, 0.10088458],
       [0.62949929, 0.2663542 , 0.83944425]])

In [19]:
b.mul(2)

tensor([[1.8408, 0.6240, 1.1925],
        [0.4174, 0.4686, 1.9983],
        [1.2707, 0.3163, 0.2018],
        [1.2590, 0.5327, 1.6789]], dtype=torch.float64)

In [20]:
a

array([[0.92039356, 0.31198323, 0.59624366],
       [0.20867766, 0.23432166, 0.99914556],
       [0.63533321, 0.15813693, 0.10088458],
       [0.62949929, 0.2663542 , 0.83944425]])

NN with pytorch

In [14]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import torch
import helper
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'grp'

In [15]:
from torchvision import datasets, transforms
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5)),])
trainset = datasets.MNIST('MNIST_data/', download=True, train=True, transform = transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

In [16]:
dataiter = iter(trainloader)
images, labels = dataiter.__next__()
print(type(images))
print(images.shape)
print(labels.shape)

RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]

In [17]:
plt.imshow(images[1].numpy().squeeze(),cmap='Greys_r')

NameError: name 'images' is not defined

In [18]:
##Solution
inputs = images.view(images.shape[0],-1)

w1 = torch.randn(784,256)
b1 = torch.randn(256)

w1 = torch.randn(256,10)
b1 = torch.randn(10)

h = activation(torch.mm(inputs,w1) + b1)
out = torch.mm(h.w2) + b2

NameError: name 'images' is not defined